[package]
name = "anni-fetch"
version = "0.1.0"
authors = ["Yesterday17 <mmf@mmf.moe>"]
license = "Apache-2.0"
description = "A library focuses on what git fetch does."
edition = "2018"

[dependencies]
ureq = "2"
miniz_oxide = "0.4.4"
sha-1 = "0.9.4"
thiserror = "1.0"
